# Primary handler settings
PRIMARY_TIMEOUT = 5.0
PRIMARY_MAX_ATTEMPTS = 3
PRIMARY_BASE_DELAY = 0.5
PRIMARY_MAX_DELAY = 10.0

# Optional handler settings
OPTIONAL_TIMEOUT = 5.0
OPTIONAL_MAX_ATTEMPTS = 3
OPTIONAL_BASE_DELAY = 0.5
OPTIONAL_MAX_DELAY = 10.0
